[project]
name = "gdr"
version = "0.1.0"
description = "Gitlab Debug Runner"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docker>=7.1.0",
    "python-gitlab>=5.6.0",
    "pyyaml>=6.0.2",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "ruff>=0.11.4",
]
